name: bitacora_frontend
description: "Aplicacion de digirey."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons
  cupertino_icons: ^1.0.8
  
  # Tus dependencias existentes
  get: ^4.7.3
  supabase_flutter: ^2.16.0
  connectivity_plus: ^7.2.0
  path_provider: ^2.1.6
  get_storage: ^2.1.1
  adaptive_theme: ^3.7.2
  action_slider: ^0.7.0
  intl: ^0.20.3
  confetti: ^0.8.0
  dropdown_search: ^7.0.0
  marquee: ^2.3.0
  uuid: ^4.6.0
  
  # Nueva dependencia del calendario horizontal
  easy_date_timeline: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# Solución para alinear las versiones de intl con easy_date_timeline
dependency_overrides:
  intl: ^0.20.3

flutter:
  uses-material-design: true
  assets:
    - assets/logos/