export 'package:bitacora_frontend/infrastructure/navigation/bindings/controllers/add_cliente.controller.binding.dart'; 
export 'package:bitacora_frontend/infrastructure/navigation/bindings/controllers/add_folios.controller.binding.dart'; 
export 'package:bitacora_frontend/infrastructure/navigation/bindings/controllers/detalles_folio.controller.binding.dart'; 
export 'package:bitacora_frontend/infrastructure/navigation/bindings/controllers/folios.controller.binding.dart'; 
export 'package:bitacora_frontend/infrastructure/navigation/bindings/controllers/home.controller.binding.dart'; 
export 'package:bitacora_frontend/infrastructure/navigation/bindings/controllers/login.controller.binding.dart'; 
export 'package:bitacora_frontend/infrastructure/navigation/bindings/controllers/profile.controller.binding.dart'; 
export 'package:bitacora_frontend/infrastructure/navigation/bindings/controllers/search_folio.controller.binding.dart'; 
export 'package:bitacora_frontend/infrastructure/navigation/bindings/controllers/success.controller.binding.dart'; 